server_tokens off;

upstream se_mentor_frontend {
    server frontend:8080;
}

upstream se_mentor_backend {
    server backend:8000;
}

server {
    listen 8080;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 8443 ssl http2;
    server_name _;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    include /etc/nginx/se-mentor-locations.conf;
}
